name: "Workflow deploy"
on:
  push:
    branches:
      - main

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to Kubernetes Engine (GKE)"
      - run: echo "This is a placeholder for the deployment step"

      
        

  
