name: Deploy to Kubernetes Engine

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hello world
        run: echo "Hello, world!"

  second_job:
    if: github.ref == 'refs/heads/main'
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: Hello again
        run: echo "Hello again, world!"
      - name: Generate file
        run: |
          echo "This is a generated file" > test.log

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: file-test
          path: test.log
