name: "Workflow deploy"
on:
  push:
    branches:
      - main

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to Cloudflare Pages
        

  
